# Definición de los valores númericos para los símbolos de LESCO


title = "LESCO identifiers"

[ids]
0="A"
1="B"
2="C"
3="CH"
4="E"
5=["D","1"]
6="F"
7="H"
8="G"
9="I"
10="J"
11="K"
12="L"
13="LL"
14="M"
15="N"
16="Ñ"
17=["O","0"]
18="P"
19="Q"
20="R"
21="RR"
22="S"
23=["T","9"]
24="U"
25=["V","2"]
26=["W","6"]
27="X"
28="Y"
29="Z"
30="3"
31="4"
32="5"
33="7"
34="8"
35="San José"
36="Alajuela"
37="Cartago"
38="Heredia"
39="Limón"
40="Guanacaste"
41="Puntarenas"
42="Yo"
43="Usted"
44="Él"
45="Nosotros"
46="Hola"
47="Adiós"
48="Repetir"
49="Por favor"
50="Despacio"
51="Perdón"
52="Mucho gusto"
53="Gracias"
54="Casa"
55="Dónde"
56="10"
57="Nombre"
58="Cumpleaños"
99=" "